# build
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - CNAME
  - Gemfile
  - LICENSE.md
  - Rakefile
  - README.md
  - vendor/
  - vnu/
  - vnu.zip
layouts: ./_layouts
sass:
  sass_dir: noita/_scss
  style: compressed
# compress layout in _layouts/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
# theme
noita:
  name: EkiNetIrc
  # description: Jekyll theme built with Foundation
  author:
    name: Anatol Broder
    url: http://penibelst.de/
  lang: fr
  topbar:
    toggle: Menu
    right:
      - name: L'équipe
        url: /equipe.html
